name: CI
on: push

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  a_test:
    runs-on: self-hosted

    name: Hi

    container:
      image: ghcr.io/clash-lang/clash-ci-8.10.7:2022-02-02

    steps:
      - name: Hello
        run: |
          echo Hello, World
